version: "3.7"

services:
  adonis_app:
    container_name: adonis_app
    networks:
      - adonis_network
    restart: always
    build:
      context: .
      target: production
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
      - 8080:8080
    env_file:
      - .env

networks:
  adonis_network:
    driver: bridge
